mybatis:
  mapper-locations: classpath:/mapper/*.xml
spring:
  datasource:
    username: root
    url: jdbc:mysql:///tieba?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
server:
  port: 9999
  max-http-header-size: 102400